### PR TITLE
update for new client.

### PR DESCRIPTION
**Pull request by jadelkhoury**
@berezovskyi Can you confirm that this is all a user needs to change? the pom dependency?

### CODE REVIEW

**Comment by berezovskyi** [comment]
No, you also need to:

- change all imports from lyo.oslc4j.client to lyo.client
- change Query related imports from lyo.oslc4j.client.resources to lyo.client.query
- change domain POJO imports from lyo.oslc4j.client.resources to lyo.domains or add a dependency for oslc-java-client-resources if not possible

**Review by berezovskyi — APPROVED** [review]

**Comment by berezovskyi** [comment]
But all of those are only needed if you used oslc4j-client before or are migrating from the v2 client

**Comment by jadelkhoury** [comment]
? But none of those are documented on the instructions I am changing.

**Comment by berezovskyi** [comment]
🤷 did not get to documenting it yet

see also https://github.com/eclipse/lyo/issues/15

**Comment by berezovskyi** [comment]
Also, the instructions above only apply to oslc4j-client upgrade. For oslc-java-client to oslc-client:


- change all imports from lyo.client.core to lyo.
- change Query related imports from lyo.client.resources to lyo.client.
- change domain POJO imports from lyo.client.resources to lyo.domains or add a dependency for oslc-java-client-resources if not possible

**Comment by jadelkhoury** [comment]
In the instructions, I only explain what dependencies they need to add for the new and old client. 
I din't explain how to use it. I don't explain how to migrate.

**Pull request merged**
