### PR TITLE
Update and Migrate the Lyo Wiki from Eclipse

### PR DESCRIPTION
**Pull request by jadelkhoury**
As initially discussed under https://github.com/eclipse/lyo/issues/8, this is a first attempt at migrating Lyo documentation.

I created a dedicated subsection for Lyo. I believe this can also replace the current "Tools & SDKs" item.

### CODE REVIEW

**Comment by jadelkhoury** [comment]
@jamsden Please note that I have not tested these pages. I have not worked out how to generate the html pages locally. But I hope the new structure is simple enough for it to work.

**Comment by jadelkhoury** [comment]
The pages migrated are 
1. Lyo front page https://wiki.eclipse.org/Lyo
2. Some of hte active eclipse wiki pages, mainly from this section https://wiki.eclipse.org/Lyo#Tutorials_and_Documentation
3. Lyo-Designer pages from the github wiki pages - https://github.com/eclipse/lyo.designer/wiki

I migrated the pages almost as-is. Some of hte pages can be shorten given their new location. I can fine tune once I read through them in the new context.

**Comment by berezovskyi** [comment]
Hej Jad, amazing effort! I managed to build the site and here are a few things I found.

No. 1: Broken link to LyoD

image

No. 2: Broken image

image

No. 3: All links under _Tutorials and Documentation > Installation_  (plus Basic Topics except for the TRS link) are broken

image

No. 4: Links under _What is OSLC?_ are broken

image

No. 5 OSLC Client Javadoc link points to Lyo 2.2.0

**Comment by berezovskyi** [comment]
Instructions for running Harp:

    harp server ./_harp
    harp compile _harp/ .

**Comment by berezovskyi** [comment]
Also, Harp works just fine without the SASS lib:

    LIBSASS_EXT="no" npm install -g harp

**Comment by jadelkhoury** [comment]
Thanks andrii.  I put this together without even testing on local machine. I’ll do another patch soon then. 
Thanks for tips on how to run.

**Comment by jadelkhoury** [comment]
Now that I can run the server locally, I have done more thourough changes.
Please review my set of entries under "Tools & SDKs for Java Developers - Eclipse Lyo".

**Comment by berezovskyi** [comment]
Thanks a lot, Jad! I have just generated the HTML and it's ready to push!

**Review by berezovskyi — APPROVED** [review]

**Comment by berezovskyi** [comment]
@jamsden I assume you are too busy to review this, so I will merge this and we will fix any of your comments afterwards.

**Comment by berezovskyi** [comment]
And it's live: http://oslc.github.io/developing-oslc-applications/

**Comment by jadelkhoury** [comment]
Thanks andrii. I will proceed and update the Lyo wiki to point here now.

**Comment by berezovskyi** [comment]
Thanks for the work, Jad!

--
–Andrew.

Från: Jad El-khoury <notifications@github.com>
Svara till: OSLC/developing-oslc-applications <reply@reply.github.com>
Datum: onsdag, 17 april 2019, W16 18:25
Till: OSLC/developing-oslc-applications <developing-oslc-applications@noreply.github.com>
Kopia: Andrii Berezovskyi <andriib@kth.se>, State change <state_change@noreply.github.com>
Ämne: Re: [OSLC/developing-oslc-applications] Update and Migrate the Lyo Wiki from Eclipse (#4)


Thanks andrii. I will proceed and update the Lyo wiki to point here now.

**Pull request merged**
