### PR TITLE
Improve the Eclipse Lyo front page to introduce Client better.

### PR DESCRIPTION
**Pull request by jadelkhoury**

### CODE REVIEW

**Review by berezovskyi — APPROVED** [review]
Thanks!

Not sure what caused the MD diff to be unreadable, hasd to review the HTML

**Comment by berezovskyi** [comment]
Side note: what do we do with the real Lyo homepage?

**Comment by jadelkhoury** [comment]
> Not sure what caused the MD diff to be unreadable, hasd to review the HTML

I had to press the "display the rich diff" instead of "display the source diff".

>Side note: what do we do with the real Lyo homepage?

https://wiki.eclipse.org/Lyo? I guess we have abandoned that a long time ago. I'm not going back :-)

**Comment by berezovskyi** [comment]
I was reviewing on my phone :)

The page I meant is https://www.eclipse.org/lyo/

**Comment by berezovskyi** [comment]
We should consider redirection, eg https://bugs.eclipse.org/bugs/show_bug.cgi?id=535276

**Comment by jadelkhoury** [comment]
I have updated a couple of links on https://www.eclipse.org/lyo/ now.

**Comment by jadelkhoury** [comment]
We can consider redirection to https://github.com/eclipse/lyo

Note that I change the https://github.com/eclipse/lyo repo's README to include the text for Contributing, etc. Maybe all other repos can simply refer to that text for example? 
See how I did with https://github.com/eclipse/lyo.core & https://github.com/eclipse/lyo.client

**Pull request merged**
